### ISSUE TITLE
Spindle-to-surface angle

### ISSUE THREAD

**Issue by TobiasKletter** [tischi/spindle3d#1]
Still getting some weird angles. I would expect A to be close to 0, and for B there is good estimate using the angle tool:

![image](https://user-images.githubusercontent.com/45814595/90144747-7dd64180-dd7f-11ea-9328-e8e3b4ed9f75.png)

Here are the input files:
A) https://www.dropbox.com/s/x8zg6cnm5a5lmtt/20190227_HighZoom--W0000--P0001-T0007--0000_42.tif?dl=0 
B) https://www.dropbox.com/s/x9q2bcm4adbk2c4/20190227_HighZoom--W0000--P0001-T0037--0001_25.tif?dl=0 

(Using the Advanced version with axial pole radius of 0.5 µm and max DNA extent of 15, everything else left at default)

**Comment by tischi** [comment]
Ok! I think there was still a bug...
 
What I now get is 
- indeed 0 degrees for `_42`
- but still 20 degrees for `_25`. 

I however think the 20 degrees could still be ok as I was drawing a 20 degrees angle into it:
![image](https://user-images.githubusercontent.com/2157566/90151506-14f2c780-dd87-11ea-9e26-7329a3a64de8.png)

Do you have one or two more examples to test?

**Comment by TobiasKletter** [comment]
@tischi 
this one should again be pretty much parallel to the surface:
https://www.dropbox.com/s/c6hxxlzk1es1llq/20190227_HighZoom--W0000--P0001-T0055--0000_58.tif?dl=0
(output was 28 degrees)

this one is more tilted:
https://www.dropbox.com/s/5smhm2w0120nta0/20190827_HighZoom--W0000--P0001-T0285--0001_26.tif?dl=0

![image](https://user-images.githubusercontent.com/45814595/90155693-e62b2000-dd8b-11ea-8dfb-ef41627eadd5.png)
(Output here was 38 degrees which I think is rather correct)

**Comment by tischi** [comment]
ok! seems to work: I am getting 0 and 28 degrees.
