### ISSUE TITLE
Sample image download

### ISSUE THREAD

**Issue by tischi** [tischi/spindle3d#21]
@TobiasKletter

I am adding a Command for downloading sample images.

How should I describe this one? 

imp = IJ.openImage("https://github.com/tischi/spindle3d/raw/master/src/test/resources/publication/20201209_R1E309_TubGFP_DM1a_KATNA1_D0_011-3.tif");

Maybe just give the cell type, which one? Something else?

**Comment by TobiasKletter** [comment]
Perhaps "Mouse embryonic stem cell expressing GFP-tagged tubulin"?

**Comment by tischi** [comment]
And how is the DNA stained?

**Comment by TobiasKletter** [comment]
Hoechst
