### ISSUE TITLE
Ground truth testing set

### ISSUE THREAD

**Issue by TobiasKletter** [tischi/spindle3d#23]
Archive contains: 

- input images (Ch1: DNA hoechst staining, Ch2: tubulin-GFP, Ch3: γ-Tubulin staining for centrosome labelling) 
- Spindle3D output images
- Spindle3D measurements

https://www.dropbox.com/s/8ztfrsky8huihtt/Spindle3D_Groundtruth_TestingSet.zip?dl=0 

- Spindle length verified by co-localisation of detected poles with centrosome staining
- Spindle axis verified in the same way
- Spindle width (average) verified by human measurements (4 spindle width measurements in the spindle axis-projected image, guided by centrosome staining and tubulin-GFP signal)
- Since spindle width as measured by Spindle3D is based on the spindle volume mask, spindle volume can also be considered verified by human spindle width (and spindle length) measurements. 
- There is no straight forward ground truth for chromatin dimensions (width, length, volume, dilation) in these images (or in any other of mine), so these were verified by visual inspection only!

The settings used for analysis

![Screenshot 2021-03-18 at 10 30 14](https://user-images.githubusercontent.com/45814595/111607009-21854580-87d8-11eb-9f55-b576e5915db7.png)

**Comment by tischi** [comment]
@TobiasKletter 

Does that mean I should use the values that are in the measurements table as ground truth?

What variance should I allow? +/- 0.5 um?

**Comment by tischi** [comment]
Does that cover different cell lines and microscopes?

It would be good if the file name contained the cell line and microscope.

**Comment by tischi** [comment]
@TobiasKletter 

Which measurements should we include in the tests?

I added now spindle width and length.

Something else? I would probably only take some that are easy to determine by eye, otherwise it is not really a GT and we are not sure if those are the values that we really want.

**Comment by TobiasKletter** [comment]
> What variance should I allow? +/- 0.5 um?

Yes sound good

> Does that cover different cell lines and microscopes?
It would be good if the file name contained the cell line and microscope.

Unfortunately not, because I only have this kind of staining (for the centrosome reference) for this cell type.
(These are all tubulin-GFP mESCs imaged on a spinning disk system)
If you feel this selection is too narrow I can try to capture and stain some HeLas

> Which measurements should we include in the tests?
I think you could even add spindle volume, even without a valid ground truth. My argument for this is, that the spindle intensity threshold in these samples was found such that the spindle mask and therefore spindle width matched the manual measurements, which could be considered the substitute ground truth. 

In any case, I think spindle length for this purpose is the most important parameter, because having a correct spindle length already 'proves' that the upstream analysis was correct

**Comment by tischi** [comment]
Why did you select 5 different ones?
Could I only use 2 for the tests? Ideally where one measurement is very different.

I think it would be important to also add examples from the other cell lines and microscopes even if the ground truth comes from just looking at it without the centrosome staining.

I would say one or two examples per microscope and cell line.

**Comment by tischi** [comment]
What about adding the spindle angle? This is in principle easy to observe manually and also it is easy for us to introduce a bug, because of all the coordinate systems.

**Comment by TobiasKletter** [comment]
OK, I will look for candidates!

> What about adding the spindle angle? This is in principle easy to observe manually and also it is easy for us to introduce a bug, because of all the coordinate systems.

Yes agreed!

**Comment by TobiasKletter** [comment]
@tischi 
https://www.dropbox.com/s/f35rjvwpa1yar6x/Spindle3D_TestingSet.zip?dl=0 

Should be a more heterogeneous selection now (width, length, angles), including different systems and magnifications!
I would suggest the following tolerances:
Spindle_Length +- 0.5 µm 
Spindle_Width_Avg +- 0.25 µm or 0.3 (a bit stricter than length, since this is the average)
Spindle_Angle +- 3° (? just a guess...)

These were the settings for all images:
![Screenshot 2021-03-24 at 10 17 23](https://user-images.githubusercontent.com/45814595/112292947-e11f3f00-8c91-11eb-894c-da530bc16007.png)

**Comment by tischi** [comment]
This looks fantastic!
Could you do me a favor and post here in the issue the GT values for the new images?
```
Spindle_Length 
Spindle_Width_Avg
Spindle_Angle
```

**Comment by TobiasKletter** [comment]
Cell_ID | Spindle_Length_um | Spindle_Width_Avg_um | Spindle_Angle_Degrees
-- | -- | -- | --
NikonSD_100x_HeLa_02 | 13.768170 | 12.184211 | 3.539942
NikonSD_60x_HeLa_02 | 13.024016 | 14.684211 | 0.858832
ZeissLSM_40x_R1EmESC_01 | 10.764525 | 8.131579 | 1.683764
NikonSD_40x_Ptk2_01 | 14.521536 | 8.657895 | 5.887710
NikonSD_60x_R1EmESC_01 | 10.550474 | 7.394737 | 5.322811
ZeissLSM_40x_CowZygote_01 | 20.202104 | 17.973684 | 10.212573
NikonSD_60x_HEK293SiRTubulin_01 | 9.630680 | 9.960526 | 11.556570
NikonSD_100x_R1EmESC_01 | 7.141428 | 7.000000 | 43.269730

**Comment by tischi** [comment]
👍 faster than ⚡

**Comment by tischi** [comment]
True for all of them?
_Ch1: DNA hoechst staining, Ch2: tubulin-GFP_

**Comment by TobiasKletter** [comment]
Sorry should have added this:

Cell_ID | Ch 1 | Ch 2 
-- | -- | -- 
NikonSD_100x_HeLa_02 | SiR DNA | Tub-GFP
NikonSD_60x_HeLa_02 | SiR DNA | Tub-GFP
ZeissLSM_40x_R1EmESC_01 | SiR DNA | Tub-GFP
NikonSD_40x_Ptk2_01 | Hoechst | Tub-YFP
NikonSD_60x_R1EmESC_01 | SiR DNA | Tub-GFP
ZeissLSM_40x_CowZygote_01 | H2B-mScarlet | mClover3-MAP4
NikonSD_60x_HEK293SiRTubulin_01 | Hoechst | SiR Tubulin
NikonSD_100x_R1EmESC_01 | SiR DNA | Tub-GFP

**Comment by tischi** [comment]
Awesome.

Every time I deploy the code this will be running and throw an error if some measurements are not within the tolerance: https://github.com/tischi/spindle3d/blob/master/src/test/java/test/TestReferenceData.java

Feels quite professional. I am happy 😃
