### ISSUE TITLE
RefinementDistance

### ISSUE THREAD

**Issue by tischi** [tischi/spindle3d#25]
@TobiasKletter

Should those go into the table??

```
  "spindlePoleARefinementDistance": 1.0606601717798212,
  "spindlePoleBRefinementDistance": 1.346291201783626,
``

**Comment by TobiasKletter** [comment]
Already in there!

**Comment by tischi** [comment]
Yes, but should they be there?
Is this interesting for the user?

**Comment by TobiasKletter** [comment]
Good point, it's probably not immediately obvious what these are.
No strong opinion from my side, so they probably can be removed from the table...

**Comment by tischi** [comment]
I will remove them from the measurements and just report them in the log window
