### ISSUE TITLE
Cell surface area

### ISSUE THREAD

**Issue by TobiasKletter** [tischi/spindle3d#30]
Hi @tischi 

for testing:
spindle:
https://www.dropbox.com/s/p93vqd3dbzw2d0p/20190227_HighZoom--W0000--P0001-T0004--0001.tif?dl=0

cell mask:
https://www.dropbox.com/s/7qq0rau685xfgwg/20190227_HighZoom--W0000--P0001-T0004--0001_CellMask.tif?dl=0

Expected value:
2488.859 µm2

**Comment by tischi** [comment]
@TobiasKletter 

Did you maybe mix up volume and surface? I get:

```
Cell_Surface_um2 = 1602.875
Cell_Volume_um3 = 2488.75
```

**Comment by TobiasKletter** [comment]
Oops, yes I did! 

But I still get a different one:
![image](https://user-images.githubusercontent.com/45814595/122362498-7449d700-cf58-11eb-83ca-d6447bd10ebc.png)

**Comment by tischi** [comment]
Are you measuring at the original resolution or at 0.25 um isotropic?

Measuring surfaces is highly non-trivial and depends a lot on the scaling: https://en.wikipedia.org/wiki/Coastline_paradox

**Comment by TobiasKletter** [comment]
Measuring at 0.25 isotropic

**Comment by tischi** [comment]
Amazing and very scary (see below), but I think that is what I said, this is not trivial.

spindleAligned 0.25 um isotropic:
<img width="174" alt="image" src="https://user-images.githubusercontent.com/2157566/122365026-99d7e000-cf5a-11eb-96d5-6e9cb5867f08.png">

dnaAligned 0.25 um isotropic:
<img width="201" alt="image" src="https://user-images.githubusercontent.com/2157566/122365053-a1978480-cf5a-11eb-9134-da6a09762b3a.png">

original orientation 0.25 um isotropic
<img width="215" alt="image" src="https://user-images.githubusercontent.com/2157566/122365084-a9efbf80-cf5a-11eb-9f37-67cb9706a947.png">

**Comment by TobiasKletter** [comment]
Oh wow this is indeed amazing and scary 👀 
Should we then stick to original orientation?

**Comment by tischi** [comment]
> Should we then stick to original orientation?

Not sure, that could also introduce a nasty bias...

**Comment by tischi** [comment]
@mcib3d do you have any suggestions for how to get a more stable Surface measurement?
Just rotating the image we are getting up to 30% differences...

**Comment by mcib3d** [comment]
Hi @tischi,

Usually I only use surface measurements to estimate shape parameters such as compactness, and I noticed quite good results when using _corrected_ surface. This measurement will try to smooth a bit the effect of binary blocs, but it is only available as pixel measurement. I guess if you want to improve your surface measurements, maybe you need to resample your image to be isotropic.

**Comment by tischi** [comment]
>  I guess if you want to improve your surface measurements, maybe you need to resample your image to be isotropic.

It is already isotropic 😃 
Could we then just multiply the "corrected" surface with the (pixel_width)^2?

**Comment by mcib3d** [comment]
yes, use the corrected surface measurement and multiply by the pixel size² :) . In the 3D ImageJ Suite the method is then `getAreaPixelsCorrected` within the `Object3DVoxels` class.

**Comment by tischi** [comment]
@mcib3d I am not sure how to instantiate the `Object3DVoxels` and how to use it. The way I did it right now I am getting a way too large surface:

<img width="1429" alt="image" src="https://user-images.githubusercontent.com/2157566/122572705-4941af00-d04e-11eb-8b08-c63cf3899161.png">

**Comment by mcib3d** [comment]
Hi @tischi,

Actually, the meaning of the value to build `Objects3DPopulation` and `Object3DVoxels` is different. For population, it will effectively refer to the threshold, but for objectVoxel it will refer to the actual label value of the object.

Since you already have a population, that is a list of generic `Object3D`, but since actually behind it is a list of `Object3DVoxels`, you can simply cast your object to `Object3DVoxels` : `object3DVoxels = (Object3DVoxels) object;`

Or, if you want to build the object directly from the image, you need its label id inside this image and build it : 
`object3DVoxels = new Object3DVoxels(id);`

**Comment by tischi** [comment]
Thanks @mcib3d,

I used this code:
```Java
                final ImageByte imageByte = new ImageByte( asImagePlus( mask, "", calibration ) );
		Objects3DPopulation objects3DPopulation = new Objects3DPopulation( imageByte, 0 );
		final Object3D object = objects3DPopulation.getObject( 0 );
		final double areaPixels = object.getAreaPixels();
		final double areaUnit = object.getAreaUnit();
		final double areaPixelsCorrected = ((Object3DVoxels) object).getAreaPixelsCorrected();
		final double areaUnitCorrected = areaPixelsCorrected * calibration.pixelWidth * calibration.pixelWidth;
		final double volumeUnit = object.getVolumeUnit();
```

And applied it to the same three images as above (same binary data but rotated).

<img width="221" alt="image" src="https://user-images.githubusercontent.com/2157566/122592776-09d28d00-d065-11eb-9704-e92e3540d50f.png">
<img width="226" alt="image" src="https://user-images.githubusercontent.com/2157566/122592806-1525b880-d065-11eb-99a5-800b67aa93f7.png">
<img width="217" alt="image" src="https://user-images.githubusercontent.com/2157566/122592836-1c4cc680-d065-11eb-89d1-9ca5f3cbcd77.png">

This seems to indicate:

1. the corrected area is very much smaller than the other one (is that expected)?
2. the ratios of the areas between the three images is pretty much the same (using corrected or not)

In MorpholibJ they have two methods: Crofton (3 dirs.) and Crofton (13 dirs.); do you think that would be also worth checking out?

**Comment by mcib3d** [comment]
Hi @tischi ,

Ok, looks interesting, yes the corrected surface is expected to be smaller as it is a kind of _smoothing_ of the voxels faces. 

I do not know much about Crofton measurement, it seems to be a method to approximate the surface area, as it relies on planes cutting the surface, as I understand, it may be more robust to rotation, worth trying then.

**Comment by tischi** [comment]
@mcib3d @dlegland

I now also tried the Crofton13 method from MLJ (`surfaceAreas`), and it so far is the method that gives the least varying results....

<img width="436" alt="image" src="https://user-images.githubusercontent.com/2157566/122755270-0d4c5b00-d295-11eb-8ff3-80e4a6b32952.png">
<img width="419" alt="image" src="https://user-images.githubusercontent.com/2157566/122755303-163d2c80-d295-11eb-9f87-36eeb85f7486.png">
<img width="416" alt="image" src="https://user-images.githubusercontent.com/2157566/122755325-1f2dfe00-d295-11eb-8ad9-bf3b12599068.png">

...however I also realized the during the image transformations the object boundary gets smoother and smoother. 

It is not obvious to me why this happens as I am using a nearest neighbor interpolation. 

Maybe this is some known effect, i.e. smoothing during resampling after transformations???


<img width="802" alt="image" src="https://user-images.githubusercontent.com/2157566/122755190-eaba4200-d294-11eb-9774-f3da8d2268e3.png">

**Comment by dlegland** [comment]
hmmm, not so surprising: whatever the interpolation method, it will result in a loss of details. If you iterate transforms, you will obtain smoothing...

An alternative would be to compute the concatenation of the transforms, and apply it to the original image. Then the interpolation (and smoothin) appears only once.

**Comment by tischi** [comment]
> If you iterate transforms, you will obtain smoothing...

This is very interesting and very good to know, indeed! I did not know it and don't find it obvious, is it?

For this particular project it is not an issue because we can simply measure the surface in the un-transformed image.
But it worried me on general grounds that the results were so different.

@TobiasKletter I would then tend to implement the Corrected Area from 3D Image Suite (in order not to have MLJ as an additional dependency in our current code) and apply this to the untransformed cell mask. OK? Can one access the Corrected Area  from the Fiji UI?

**Comment by TobiasKletter** [comment]
@tischi Yes agreed! 
I haven't spotted the Corrected Area measurement so far!

**Comment by tischi** [comment]
Should I anyway do it?

**Comment by TobiasKletter** [comment]
Yes
Or is there a drawback if it's not accessible through the GUI?

**Comment by tischi** [comment]
Not for me. I will do it.

**Comment by mcib3d** [comment]
The _corrected area_ value is available within the **3D Manager.**

**Comment by tischi** [comment]
@TobiasKletter I pushed to the update site. Does it work?

**Comment by TobiasKletter** [comment]
@tischi It works, but it's not giving the value for the untransformed but for the spindle-aligned cell mask (1089 um2) in the sample image.

**Comment by tischi** [comment]
I changed it. Better now?

**Comment by TobiasKletter** [comment]
Yes 👍
