### ISSUE TITLE
icon

### ISSUE THREAD

**Issue by tischi** [tischi/spindle3d#4]
@TobiasKletter

Could we use one of your nice drawings as an icon for this site?

**Comment by TobiasKletter** [comment]
Of course!
So I have the more "naturalist" version like the left one and I have more clean version:
![image](https://user-images.githubusercontent.com/45814595/90238766-bbda7080-de26-11ea-91c6-4aee9631db07.png)


I prefer the right one as a logo or icon. What do you think?

**Comment by tischi** [comment]
Beautiful!
I prefer the left one, also because it does look much more 3D.

**Comment by tischi** [comment]
I made a version with text included. What do you think?
![image](https://user-images.githubusercontent.com/2157566/90240725-175a2d80-de2a-11ea-9f6f-bf996ecea118.png)

**Comment by TobiasKletter** [comment]
Looks cool :) If needed, I can also upload the vector files or higher resolutions...
