### ISSUE TITLE
DNA intermediate results images

### ISSUE THREAD

**Issue by TobiasKletter** [tischi/spindle3d#7]
Hi!
These are new:
![image](https://user-images.githubusercontent.com/45814595/92586258-5008ed80-f296-11ea-95c5-15c8ab4f7641.png)

1. They show the rotated and aligned DNA, right? 
2. During analysis, they are opened whether or not "show intermediate results" is ticked. When batch-processing many input images, this might lead to memory issues at some point, no?

**Comment by tischi** [comment]
My mistake, I added this for debugging, I will remove it....

**Comment by tischi** [comment]
@TobiasKletter 

Could you please update Fiji and try again?

**Comment by TobiasKletter** [comment]
Solved :) Thanks
