### ISSUE TITLE
Segmentation artifacts

### ISSUE THREAD

**Issue by TobiasKletter** [tischi/spindle3d#9]
In rare cases, this happens:

![Screenshot 2020-09-16 at 15 01 29](https://user-images.githubusercontent.com/45814595/93340916-c4f79c80-f82d-11ea-9004-e61b8a983391.png)
https://www.dropbox.com/s/a99atgrng1fshz7/lid_g01_R3D_D3D-2.tif?dl=0

Tubulin signal in this sample is not optimal to begin with, but to me, this looks like the spindle mask extends into "void" voxels, no?

Edit: Another example:
![image](https://user-images.githubusercontent.com/45814595/93344906-84e6e880-f832-11ea-9b42-60ca893f083f.png)
https://www.dropbox.com/s/6gcehlhf0g1fgb3/lid_x01_R3D_D3D-1.tif?dl=0

**Comment by tischi** [comment]
I think here the issue is that the DNA is much fatter along the axial direction as usual... 
I am checking this.

**Comment by tischi** [comment]
The other issue is that the imaging along the z-axis stopped too early. Thus the Spindle in fact is touching the image boundary. Probably the best would be to automatically spot this and throw an error, right?

![image](https://user-images.githubusercontent.com/2157566/95563949-5ec1fc00-0a1e-11eb-8582-eb28406efe7a.png)

**Comment by tischi** [comment]
Another suggestion: We could also QC on the difference between the spindle and the cytoplasm signal.

For this data set: https://www.dropbox.com/s/a99atgrng1fshz7/lid_g01_R3D_D3D-2.tif?dl=0

Is it like this: 

```
Tubulin intensity cytoplasm (mean +/- sdev): 170 +/- 45; numPixels: 25646
Tubulin intensity spindle (mean +/- sdev): 228 +/- 73; numPixels: 2048
```

```
170 + 45 = 215
228 - 73 = 155
```

That means the signals overlap quite a bit in terms of their intensities.
Maybe we should automatically dump such data?

What do you think?

Could you link to a data set that does not have this issue such that we can compare this?

**Comment by TobiasKletter** [comment]
1) The issue often arrises when I have to crop the imput images drastically as a measure to salvage the analysis. In busy images, bright signals in both channels from densely packed neighouring cells (dead or alive, below and above...) causes the analysis to abort or make mistakes. I noticed, both can be helped when the mitotic cell of interest is cropped more and more to exclude the perturbing voxels - after cropping, the "good" signals ended up touching the image border. I will look for a couple of examples that illustrate this. Maybe we can find a solution that targets the origin of the issue and not the symptom...

2) I think it's a good idea to have some sort of quality control for this, but maybe it would be enough to write it in the "comment" section of the output table instead of dumping the analysis? So that the user gets the output + registered image as usual, but with the disclaimer that spindle signal-to-background is weak and might yield incorrect measurements?
These images will probably not have the issue, for testing:
https://www.dropbox.com/s/6b5l4qssmrtq9ou/20190827_T0145_C.tif?dl=0
https://www.dropbox.com/s/rrcof8s3me2ac7l/20190827_T0248_A.tif?dl=0

**Comment by tischi** [comment]
> Maybe we can find a solution that targets the origin of the issue and not the symptom...

Sounds like a good idea. You could open a new issue about the distracting bright objects.

>  These images will probably not have the issue, for testing:

### ok
```
Tubulin intensity cytoplasm (mean +/- sdev): 15 +/- 14; numPixels: 18264
Tubulin intensity spindle (mean +/- sdev): 67 +/- 22; numPixels: 5416
> ( 67 - 15 ) / sqrt( 22^2 + 14^2 )
[1] 1.994109
```

### bad
```
Tubulin intensity cytoplasm (mean +/- sdev): 170 +/- 45; numPixels: 25646
Tubulin intensity spindle (mean +/- sdev): 228 +/- 73; numPixels: 2048
> (228 - 170) / sqrt(73^2 + 45^2)
[1] 0.6763417
```

What about I just add the `Spindle_SNR` as defined above as a measurement. And then users can filter on this number?

**Comment by tischi** [comment]
I added `Spindle_SNR` to the measurements.

1. Could please you check the values? I think below 1.0 may be critical.
1. Could please you make a note in the publication that we talk about this?

**Comment by TobiasKletter** [comment]
> > Maybe we can find a solution that targets the origin of the issue and not the symptom...
> 
> Sounds like a good idea. You could open a new issue about the distracting bright objects.

Will do!

> Could please you check the values? I think below 1.0 may be critical.
> Could please you make a note in the publication that we talk about this?

👍
